<?php

/**
 * Page Tree Per User
 * based on PageEditPerUser
 *
 * Copyright 2014 by Nico Knoll
 * http://nico.is
 *
 */

class PageTreePerUser extends WireData implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Page Tree Per User', 
			'version' => 1, 
			'summary' => 'Choose a root page for the page tree per user.',
			'singular' => true, 
			'autoload' => true, 
			);
	}

	/**
	 * Attach our hooks
	 *
	 */
	public function init() {
		$this->addHookBefore('ProcessPageList::execute', $this, 'hookPageList'); 
	}


	/**
	 * ProcessPageList hook
	 *
	 */
	public function hookPageList($event) {
		// set it to the choosen page or if a page is chosen
		if(!($this->user->pagetree_root_page instanceof NullPage)) {
			$event->object->set('id', $this->user->pagetree_root_page->id);
		}
	}

	/**
	 * Install the module and add the 'pagetree_root_page' field to the user template
	 *
	 */
	 
	public function ___install() {
		$field = new Field(); 
		$field->name = 'pagetree_root_page';
		$field->label = 'Root page in page tree for this user';
		$field->labelFieldName = 'path';
		$field->type = wire('modules')->get('FieldtypePage'); 
		$field->inputfield = 'InputfieldPageListSelect';
		$field->set('derefAsPage', 2);
		$field->save();

		$fieldgroup = $this->fieldgroups->get('user');
		$fieldgroup->add($field);
		$fieldgroup->save();

		$this->message("Added field 'pagetree_root_page' to the user template.");
	}

	/**
	 * Uninstall 'pagetree_root_page' field
	 *
	 */
	 
	public function ___uninstall() {
		$field = $this->fields->get('pagetree_root_page');
		$fieldgroup = $this->fieldgroups->get('user');
		if($field && $fieldgroup) {
			$fieldgroup->remove($field);
			$fieldgroup->save();
		}
		$this->fields->delete($field);
		$this->message("Removed field: pagetree_root_page");
	}

}

